### ISSUE TITLE
motors do not stop

### ISSUE THREAD

**Issue by renebohne** [Augmented-Robotics/roboheart-arduino-library#2]
the app does not send a stop command if the "sticks" are let gone.
We might want to add a failsafe or timeout to the firmware, stopping the motors if no drive commands are received within a certain time.

**Comment by evgenimelan** [comment]
Please use the newest app on Playstore and Appstore:
https://play.google.com/store/apps/details?id=com.AugmentedRobotics.RoboHeartControl 
https://apps.apple.com/us/app/roboheart-control/id6447350006
